In [51]:
from statistics import mean
import numpy as np
from math import factorial
import csv
import copy
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from numpy import mean
from sklearn.metrics import r2_score
import pickle
import features
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix


In [52]:
class CSV_:
    def __init__(self, path):
        self.CSVfilePath = path

    def readCSV_board(self, file_address=''):
        if len(file_address) == 0:
            file_address = self.CSVfilePath
        board_list = []
        cost_list = []
        with open(file_address, mode='r')as file:
            csvFile = csv.reader(file)
            # first line is the length of board
            board_size = int(next(csvFile)[0])
            index = 0
            for lines in csvFile:
                # only when there are blank lines
                if index == 0:
                    board = []  # new board will start after cost
                    # continue
                if index < board_size:
                    board.append(list(lines))
                    index += 1
                    continue
                if index == board_size:
                    for i in range(0, len(board)):
                        for j in range(0, len(board)):
                            board[j][i] = int(board[j][i])
                    board_list.append(board)
                    cost_list.append(int(lines[0]))
                    index = 0
                    # print(board)
                    continue
        file.close()
        return board_list, cost_list


In [53]:
# class Board_Features:
#     def __init__(self, pattern, cost):
#         self.features = features.Features(pattern)
#         self.pattern = pattern
#         self.cost = cost
#         self.size = len(self.pattern)
#         self.heaviest_queen = self.features.Heaviest_Queen()
#         self.lightest_queen = self.features.Lightest_Queen()
#         self.total_weight = self.features.Total_Weight()
#         self.ratio_heavy_to_light = self.features.Ratio_Heavy_to_Light()
#         self.mean_weight = self.features.Mean_weight()
#         self.median_weight = self.features.Median_weight()
#         self.attacking_pairs = self.features.Pairs_Attacking_Queens()
#         self.heuristic_1 = self.features.heuristic_1()
#         self.heuristic_2 = self.features.avdist()
#         self.heuristic_3 = self.features.avang()
#         self.heuristic_4 = self.features.avweightedcoord()
#         self.heuristic_5 = self.features.heuristic_5()


def get_data(path):
    csv_ = CSV_("C:/Users/Tanish A. Mishra/Documents/College Stuff/WPI/CS534/Assignment 3/N-Queens-Problem-using-planning-algorithms-main/Machine-Learning-Approach/Data_5_new.txt")
    board_list,  cost_list = csv_.readCSV_board("C:/Users/Tanish A. Mishra/Documents/College Stuff/WPI/CS534/Assignment 3/N-Queens-Problem-using-planning-algorithms-main/Machine-Learning-Approach/Data_5_new.txt")
    return board_list, cost_list


board_list, cost_list = get_data("C:/Users/Tanish A. Mishra/Documents/College Stuff/WPI/CS534/Assignment 3/N-Queens-Problem-using-planning-algorithms-main/Machine-Learning-Approach/Data_5_new.txt")



In [54]:
#print(cost_list[5])
for i in range(len(board_list)):
    board_list[i]=np.reshape(np.array(board_list[i]),(len(board_list[i])**2))
board_list=np.array(board_list)


In [55]:
print(np.shape(board_list))


(50000, 25)


In [56]:
X_train, X_test, y_train, y_test = train_test_split(board_list, cost_list, test_size=0.20, random_state=None)


In [57]:
print(X_train)


[[0 0 0 ... 5 0 0]
 [5 0 2 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [4 0 0 ... 0 6 0]
 [0 0 3 ... 0 0 0]]


In [64]:
mlp = MLPRegressor(hidden_layer_sizes=(15,5), activation='relu', solver='adam', max_iter=1000)
mlp.fit(X_train,y_train)

MLPRegressor(hidden_layer_sizes=(15, 5), max_iter=1000)

In [65]:
ypred=mlp.predict(X_test)
r2err=r2_score(y_test,ypred)

In [66]:
print(r2err)

0.8766436027358291


In [67]:
filename='nnmodel.sav'
pickle.dump(mlp,open(filename,'wb'))

In [ ]:
loadedmlp=pickle.load(open(filename,'rb'))